# Generated by Django 6.1 on 2026-09-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ_attrition_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employ_data_hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DistanceFromHome', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('DailyRate', models.CharField(max_length=100)),
                ('EnvironmentSatisfaction', models.CharField(max_length=100)),
                ('JobInvolvement', models.CharField(max_length=100)),
                ('JobLevel', models.CharField(max_length=100)),
                ('JobRole', models.CharField(max_length=100)),
                ('JobSatisfaction', models.CharField(max_length=100)),
                ('MaritalStatus', models.CharField(max_length=100)),
                ('MonthlyIncome', models.CharField(max_length=100)),
                ('NumCompaniesWorked', models.CharField(max_length=100)),
                ('OverTime', models.CharField(max_length=100)),
                ('RelationshipSatisfaction', models.CharField(max_length=100)),
                ('StockOptionLevel', models.CharField(max_length=100)),
                ('TotalWorkingYears', models.CharField(max_length=100)),
                ('TrainingTimesLastYear', models.CharField(max_length=100)),
                ('WorkLifeBalance', models.CharField(max_length=100)),
                ('YearsAtCompany', models.CharField(max_length=100)),
                ('YearsInCurrentRole', models.CharField(max_length=100)),
                ('YearsWithCurrManager', models.CharField(max_length=100)),
            ],
        ),
    ]
