# Generated by Django 6.1 on 2026-09-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employ_attrition_app', '0002_employ_data_hist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employ_data_hist',
        ),
    ]
