# Generated by Django 6.1 on 2026-09-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ_attrition_app', '0003_delete_employ_data_hist'),
    ]

    operations = [
        migrations.CreateModel(
            name='employ_data_hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(max_length=100)),
                ('JobRole', models.CharField(max_length=100)),
                ('MonthlyIncome', models.CharField(max_length=100)),
                ('OverTime', models.CharField(max_length=100)),
                ('Attrition', models.CharField(max_length=100)),
                ('probability', models.CharField(max_length=100)),
            ],
        ),
    ]
